version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    build:
      context: zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: kafka
    build:
      context: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

networks:
  default:
    external:
      name: etl-net
